version: '3.8'
services:
  frontend:
    build:
      context: ./nuxt-app
      dockerfile: Dockerfile
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./nuxt-app:/app
      - /app/node_modules
    ports:
      - '9000:3000'
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: ./express-app
      dockerfile: Dockerfile
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./express-app:/app
      - /app/node_modules
    ports:
      - '9001:3000'
    environment:
      - NODE_ENV=development
    command: npm run dev 