# This file configures Netlify's build and deployment settings.

[build]
  # Set the base directory to your Nuxt app's folder.
  # Netlify will run the build command from this directory.
  base = "nuxt-app"

  # The command to build your Nuxt site.
  command = "yarn build"

  # The directory where the built site is located, relative to the `base` directory.
  # For Nuxt 3, this is typically ".output/public".
  publish = ".output/public" 