# This file configures Netlify's build and deployment settings.

[build]
  # The command to build your Nuxt site. We change into the nuxt-app directory
  # before running the installation and build.
  command = "cd nuxt-app && yarn install && yarn build"

  # The directory where the built site is located, relative to the repository root.
  publish = "nuxt-app/.output" 