[build]
  command = "(cd express-app && npm install) && (cd nuxt-app && npm install && npm run build)"
  publish = "nuxt-app/.output/public"
  base = ""

# Optionally, you can add [functions] if you use Netlify Functions